CC = gcc
CFLAGS=-Wall


all: main

reverse: main.c
	$(CC) $(CFLAGS) -o $@ $^

test: main
	./main /home/students/s/surdpawe/Dokumenty/cw2
	./main /home/students/s/surdpawe/Muzyka

clean:
	rm -rf main

